(()=>{'use strict';
const $=s=>document.querySelector(s),root='assets/hamuketsu/';let chosen=null,returnFocus=null,photoRequest=0,rewardRequest=0;
const owns=c=>Journey.progress.collection.includes(c.collection_id);
async function loadPair(c,token){const slots=[$('#photo-butt-slot'),$('#photo-face-slot')];slots.forEach(s=>{s.replaceChildren();s.textContent='よみこみ中…'});const imgs=[new Image(),new Image()];imgs[0].src=root+c.butt_file;imgs[1].src=root+c.face_file;try{await Promise.all(imgs.map(i=>i.decode()));if(token!==photoRequest)return;imgs.forEach((i,j)=>{i.alt=j?'おかお':'はむケツ';i.classList.toggle('silhouette',!owns(c));slots[j].replaceChildren(i)})}catch{if(token===photoRequest)slots.forEach(s=>s.textContent='画像を読み込めませんでした')}}
const image=(file,name)=>{const img=document.createElement('img');img.src=root+file;img.alt=name;img.loading='lazy';return img};
function openPhoto(c){chosen=c;returnFocus=document.activeElement;const s=Journey.stages[Number(c.stage.split('-')[1])-1];$('#photo-name').textContent=owns(c)?c.display_name:'???';$('#photo-number').textContent='No. '+c.collection_id;$('#photo-info').textContent=`WORLD ${c.stage}\n${s.name}\n${c.clear_count}回クリアすると GET`;$('#photo-story').textContent=owns(c)?`${c.display_name}の はむケツ。\n${s.name}を ${c.clear_count}回クリアした 思い出だよ！`:`WORLD ${c.stage}を ${c.clear_count}回クリアすると\nこの はむケツに あえるよ。`;$('#favorite-note').textContent='';updateFavorite();loadPair(c,++photoRequest);$('#photo-panel').hidden=false;$('#photo-close').focus()}
function updateFavorite(){$('#photo-favorite').hidden=!owns(chosen);$('#photo-favorite').textContent=Journey.progress.favorites.includes(chosen.collection_id)?'推しケツから はずす':Journey.progress.favorites.length===10?'推しケツを入れ替える':'推しケツ10選に 飾る'}
function refreshHome(){const host=$('#home-photos');host.replaceChildren();for(const [n,id] of Journey.progress.favorites.entries()){const c=HAMUKETSU.find(c=>c.collection_id===id),b=document.createElement('button'),[l,t,r,bt,w,h]=PHOTO_BOUNDS[c.butt_file];b.className='home-photo';b.setAttribute('aria-label',c.display_name+'を拡大');b.title=c.display_name;b.style.left=((218+(n%5)*139)/960*100)+'%';b.style.top=((n<5?60:135)/540*100)+'%';b.innerHTML=`<svg preserveAspectRatio="xMidYMax meet" viewBox="${l} ${t} ${r-l} ${bt-t}" aria-hidden="true"><image href="${root+c.butt_file}" width="${w}" height="${h}"/></svg>`;b.onclick=()=>openPhoto(c);host.append(b)}$('#save-note').textContent=Journey.storageOK?`ハムケツ ${Journey.progress.collection.length} / 30　推しケツ ${Journey.progress.favorites.length} / 10　· 自動保存`:'保存できません。ブラウザの保存設定を確認してね。';fitHome()}
function fitHome(){$('#home-photos').style.width=(960/document.querySelector('canvas').width*100)+'%'}addEventListener('hamusubi-fit',fitHome);
function album(){const grid=$('#album-grid');grid.replaceChildren();$('#album-count').textContent=`${Journey.progress.collection.length} / 30`;for(const c of HAMUKETSU){const own=owns(c),b=document.createElement('button');const favorite=Journey.progress.favorites.includes(c.collection_id);b.className='album-card'+(favorite?' is-favorite':'');if(favorite){const badge=document.createElement('span');badge.className='favorite-badge';badge.textContent='♥ 推し';b.append(badge)}const img=image(c.butt_file,own?c.display_name:'未取得のシルエット');img.classList.toggle('silhouette',!own);b.append(img);const title=document.createElement('strong');title.textContent=own?c.display_name:'???';const hint=document.createElement('small');hint.textContent=`No.${c.collection_id} · WORLD ${c.stage} · ${c.clear_count}回`;b.append(title,hint);b.onclick=()=>openPhoto(c);grid.append(b)}$('#album-panel').hidden=false;$('#album-close').focus()}
$('#favorites-clear').onclick=()=>{Journey.progress.favorites=[];Journey.save();refreshHome();album()};$('#album-bottom-close').onclick=()=>$('#album-close').click();$('#album-open').onclick=album;$('#album-close').onclick=()=>{$('#album-panel').hidden=true;$('#album-open').focus()};$('#photo-close').onclick=()=>{photoRequest++;$('#photo-panel').hidden=true;returnFocus?.focus()};function afterFavorite(copy){updateFavorite();$('#favorite-note').textContent=copy;refreshHome();if(!$('#album-panel').hidden){const focus=document.activeElement;album();focus?.focus()}}
function exchange(){const list=$('#exchange-list');list.replaceChildren();for(const id of Journey.progress.favorites){const c=HAMUKETSU.find(c=>c.collection_id===id),b=document.createElement('button');b.append(image(c.butt_file,c.display_name));const n=document.createElement('span');n.textContent=c.display_name;b.append(n);b.onclick=()=>{if(Journey.replaceFavorite(id,chosen.collection_id)){ $('#exchange-panel').hidden=true;afterFavorite('入れ替えたよ！ 10 / 10');$('#photo-favorite').focus()}};list.append(b)}$('#exchange-panel').hidden=false;$('#exchange-cancel').focus()}
$('#exchange-cancel').onclick=()=>{$('#exchange-panel').hidden=true;$('#photo-favorite').focus()};
$('#photo-favorite').onclick=()=>{if(Journey.progress.favorites.length===10&&!Journey.progress.favorites.includes(chosen.collection_id)){exchange();return}if(Journey.toggleFavorite(chosen.collection_id))afterFavorite('いま '+Journey.progress.favorites.length+' / 10 飾ってるよ')};$('#home-erase').onclick=()=>{$('#confirm-panel').hidden=false;$('#erase-cancel').focus()};
const url=()=>location.href.split('#')[0].split('?')[0];const shareText='はむすび🍙で遊んでるよ！\n\nハムスターでいろんな場所へ冒険に出かけよう！\nおにぎり🍙を集める小さな冒険🐹\n#はむチラ #ハムスター';
$('#share-open').onclick=()=>{window.ShelfShare?.reset();$('#share-title').textContent='はむすびを シェア';$('#share-x').href='https://twitter.com/intent/tweet?text='+encodeURIComponent(shareText)+'&url='+encodeURIComponent(url());$('#share-line').href='https://line.me/R/msg/text/?'+encodeURIComponent(shareText+'\n'+url());$('#share-status').textContent='';$('#share-panel').hidden=false;$('#share-close').focus()};$('#share-close').onclick=()=>{$('#share-panel').hidden=true;$('#share-open').focus()};$('#copy-url').onclick=async()=>{try{await navigator.clipboard.writeText(url());$('#share-status').textContent='URLをコピーしたよ！'}catch{const t=document.createElement('textarea');t.value=url();$('#share-status').replaceChildren(t);t.select();if(document.execCommand('copy'))$('#share-status').textContent='URLをコピーしたよ！';else $('#share-status').append(' このURLをコピーしてね。')}};
$('#reward-close').onclick=()=>{rewardRequest++;$('#reward-panel').hidden=true;refreshHome()};
window.CollectionUI={openPhoto,refreshHome,blocked:()=>['album-panel','photo-panel','share-panel','reward-panel','confirm-panel','exchange-panel','treasure-help'].some(id=>!$('#'+id).hidden),async reward(c){const token=++rewardRequest,slot=$('#reward-slot');slot.replaceChildren();slot.textContent='よみこみ中…';$('#reward-name').textContent=c.display_name;$('#reward-panel').hidden=false;$('#reward-close').focus();const img=new Image();img.src=root+c.butt_file;img.alt=c.display_name;try{await img.decode();if(token===rewardRequest)slot.replaceChildren(img)}catch{if(token===rewardRequest)slot.textContent='画像を読み込めませんでした'}refreshHome()}};
refreshHome();
})();
