(()=>{'use strict';
const KEY='hamusubi.events.v1',fresh=()=>({version:1,records:{},owned:{},selected:{},seen:[],campaignStats:{},titles:{},equippedTitle:null,changes:{fur:0,furniture:0}});
let data=fresh();try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw?.version===1)data={...fresh(),...raw}}catch{}
const definitions=[...(window.HAMUSUBI_EVENTS||[])].sort((a,b)=>(a.order||0)-(b.order||0)),rewards=window.HAMUSUBI_EVENT_REWARDS||[],images=new Map();let current=null,run=null;
const force=false; // Reward placement testing is disabled.
const datePreview=['localhost','127.0.0.1','[::1]','192.168.0.13'].includes(location.hostname)&&new URLSearchParams(location.search).get('eventPreview')==='1';
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function active(e,now=Date.now()){return !!e&&e.enabled===true&&(datePreview||(now>=Date.parse(e.startsAt)&&now<Date.parse(e.endsAt)))}
const record=id=>data.records[id]||{plays:0,clears:0,bestScore:0,bestRice:0,top:[],items:{}};
function unlockCondition(e){if(e.mode==='hard')return 'NORMAL '+e.number+'をクリアで解放';return e.number>1?'NORMAL '+(e.number-1)+'をクリアで解放':''}function unlocked(e){if(e.mode==='hard')return record(e.campaignId+'-normal'+e.number).clears>0;return e.number===1||record(e.campaignId+'-normal'+(e.number-1)).clears>0}function eligible(e){return active(e)&&unlocked(e)&&e.stage&&typeof e.background==='string'&&Array.isArray(e.rewards)&&e.rewards.every(id=>rewards.some(r=>r.rewardId===id&&r.asset&&r.preview))}
function value(c,r){switch(c.type){case 'clear':return r.clears;case 'score':return r.bestScore;case 'item':return r.items[c.itemId]||0;case 'rice':return r.bestRice;default:return 0}}
function met(c,r){if(c.type==='all')return c.conditions.every(x=>met(x,r));if(c.type==='any')return c.conditions.some(x=>met(x,r));return value(c,r)>=(c.target??1)}
function progress(c,r){if(c.type==='all'||c.type==='any')return c.conditions.map(x=>progress(x,r)).join(c.type==='all'?' ＋ ':' または ');return (c.label||({clear:'クリア',score:'ベストスコア',item:'専用アイテム',rice:'はむすび'})[c.type])+' '+value(c,r)+' / '+(c.target??1)}
function normalCleared(id){return definitions.filter(e=>e.campaignId===id&&e.mode==='normal'&&record(e.eventId).clears>0).length}
function campaignValue(type,id){if(type==='normalAll')return normalCleared(id);if(type==='campaignScore')return Math.max(0,...definitions.filter(e=>e.campaignId===id).map(e=>record(e.eventId).bestScore));if(type==='campaignClears')return definitions.filter(e=>e.campaignId===id).reduce((n,e)=>n+record(e.eventId).clears,0);if(type==='periodRainbow')return definitions.filter(e=>e.campaignId===id).reduce((n,e)=>n+(record(e.eventId).items?.rainbow||0),0);if(type==='complete')return rewards.filter(r=>r.eventId===id&&r.condition.type!=='complete'&&data.owned[r.rewardId]).length;return 0}
function campaignMet(c,id){if(c.type==='any')return c.conditions.some(part=>campaignMet(part,id));if(c.type==='all')return c.conditions.every(part=>campaignMet(part,id));return campaignValue(c.type,id)>=c.target}
function award(e){if(!active(e))return;for(const id of e.rewards){const reward=rewards.find(r=>r.rewardId===id);if(reward&&!data.owned[id]&&(reward.eventId?campaignMet(reward.condition,reward.eventId):met(reward.condition,record(e.eventId)))){data.owned[id]={eventId:e.eventId,rewardId:id,acquiredAt:new Date().toISOString()};if(run)run.awards.push(id);const copy='イベントミッション達成！ '+reward.name+'を手に入れた！ カスタムで使えるようになったよ！';Missions.queue.push(copy);if(window.HomeGame?.mode()==='play')HomeGame.notice(copy)}}save()}
function start(id){const e=definitions.find(e=>e.eventId===id);if(!eligible(e))return null;current=e;run={collected:new Set(),awards:[]};data.records[id]={...record(id),plays:record(id).plays+1};save();return JSON.parse(JSON.stringify(e.stage))}
function collect(token,itemId){if(!current||!run||!active(current)||run.collected.has(token))return;run.collected.add(token);const r=data.records[current.eventId];r.items[itemId]=(r.items[itemId]||0)+1;award(current)}
function clear(score,rice){if(!current||!active(current)||run.finished)return;run.finished=true;const r=data.records[current.eventId];r.clears++;r.bestScore=Math.max(r.bestScore,score);r.bestRice=Math.max(r.bestRice,rice);r.top=[...r.top,score].sort((a,b)=>b-a).slice(0,3);award(current);window.Seasonal?.checkTitles()}
function asset(path){if(!images.has(path)){const im=new Image();im.src=path;images.set(path,im)}return images.get(path)}
function owned(kind){return rewards.filter(r=>data.owned[r.rewardId]&&r.category===kind)}
const previewSelections={};function selected(kind){if(force&&previewSelections[kind])return rewards.find(r=>r.rewardId===previewSelections[kind]);return owned(kind).find(r=>r.rewardId===data.selected[kind])}
function preview(r){const im=document.createElement('img');im.src=r.preview;im.alt=r.name;im.className='design-preview';im.style.objectFit='contain';return im}
function decorate(){const p=document.querySelector('#upgrade-body');if(!p||document.querySelector('#upgrade-panel').hidden)return;const page=document.querySelector('#upgrade-panel').dataset.page;if(page==='adventure'){const events=definitions.filter(eligible);if(!events.length)return;const h=document.createElement('h3');h.textContent='イベントおでかけ';p.append(h);const row=document.createElement('div');row.className='event-cards';for(const e of events){const b=document.createElement('button');b.textContent=(e.icon||'★')+' '+e.name;b.onclick=()=>show(e.eventId);row.append(b)}p.append(row)}}
function show(id){const e=definitions.find(e=>e.eventId===id);if(!eligible(e)){HomeGame.goHome();HomeGame.notice('このイベントは終了しました。');return}const panel=document.querySelector('#upgrade-panel'),body=document.querySelector('#upgrade-body');panel.dataset.page='event';panel.hidden=false;document.querySelector('#upgrade-title').textContent=e.name;body.replaceChildren();const desc=document.createElement('p');desc.textContent=e.description+' ／ '+new Date(e.endsAt).toLocaleString()+'まで';body.append(desc);for(const id of e.rewards){const r=rewards.find(r=>r.rewardId===id),card=document.createElement('article');card.className='event-reward';const text=document.createElement('p');text.textContent='イベント限定報酬：'+r.name+'\n'+r.description+'\n'+progress(r.condition,record(e.eventId))+(data.owned[id]?' ／ 取得済み':'');card.append(preview(r),text);body.append(card)}const play=document.createElement('button');play.textContent='イベントへおでかけ';play.onclick=()=>HomeGame.beginEvent(id);const back=document.createElement('button');back.textContent='どこへおでかけする？ に戻る';back.onclick=()=>HomeUpgrade.adventure();body.append(play,back)}
let noticeObserver=null;
function unseenReward(id){return !!data.owned[id]&&!data.seen.includes(id)}
function categoryUnseen(kind){return owned(kind).some(r=>unseenReward(r.rewardId))}
function addNews(card){const badge=document.createElement('b');badge.className='custom-new-badge';badge.textContent='!';badge.setAttribute('aria-label','新しく解放');card.append(badge)}
function paintSelection(kind,body){for(const b of body.querySelectorAll('[data-custom-id]')){const isEvent=b.dataset.customEvent==='true',selected=isEvent?data.selected[kind]===b.dataset.customId:!selectedReward(kind)&&Missions.data.selected[kind]===b.dataset.customId;const chosen=kind==='bowl'&&!isEvent?!selectedReward(kind):selected;b.classList.toggle('chosen',chosen);b.setAttribute('aria-pressed',String(chosen));let badge=b.querySelector('.custom-equipped-badge');if(chosen&&!badge){badge=document.createElement('b');badge.className='custom-equipped-badge';badge.textContent='使用中';b.append(badge)}if(badge)badge.hidden=!chosen;}}
function selectedReward(kind){return selected(kind)}
function customCards(kind,body){noticeObserver?.disconnect();const list=owned(kind);if(list.length){const h=document.createElement('h3');h.textContent='イベント限定';body.append(h);const grid=document.createElement('div');grid.className='upgrade-grid design-grid';for(const r of list){const b=document.createElement('button');b.dataset.customId=r.rewardId;b.dataset.customEvent='true';b.append(preview(r));const label=document.createElement('strong');label.textContent=r.name+' · EVENT';b.append(label);if(unseenReward(r.rewardId))addNews(b);b.onclick=()=>{if(data.selected[kind]!==r.rewardId)window.Seasonal?.changed(kind);data.selected[kind]=r.rewardId;if(!data.seen.includes(r.rewardId))data.seen.push(r.rewardId);save();paintSelection(kind,body)};grid.append(b)}body.append(grid)}paintSelection(kind,body);
// Only acknowledge a newly unlocked item once its card is actually visible.
noticeObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const id=entry.target.dataset.customId;if(unseenReward(id)){data.seen.push(id);save()}noticeObserver.unobserve(entry.target)}},{root:document.querySelector('#upgrade-panel'),threshold:.5});for(const b of body.querySelectorAll('[data-custom-event]'))if(unseenReward(b.dataset.customId))noticeObserver.observe(b);
}

window.EventSystem={KEY,categoryUnseen,addNews,paintSelection,unlocked,unlockCondition,previewEnabled:force,previewSelections,previewEquip(id){if(!force)return;const r=rewards.find(r=>r.rewardId===id);if(r)previewSelections[r.category]=id},previewReset(){for(const k of Object.keys(previewSelections))delete previewSelections[k]},get data(){return data},get current(){return current},get recentRewards(){return (run?.awards||[]).map(id=>rewards.find(r=>r.rewardId===id))},normalCleared,campaignValue,definitions,rewards,active,eligible,record,progress,start,collect,clear,leave(){current=null;run=null},save,award,owned,selected,asset,preview,decorate,show,customCards,clearSelection(kind){delete data.selected[kind];save()},markSeen(){data.seen=Object.keys(data.owned);save()},unseen:()=>Object.keys(data.owned).some(id=>!data.seen.includes(id)),restore(raw){data={...fresh(),...(raw||{})};current=null;run=null}};
})();
