// Display-only localization. Never changes gameplay data, item IDs or save schemas.
(()=>{'use strict';
const dictionary=window.HAMUSUBI_TRANSLATIONS,KEY='hamusubi.language.v1',supported=['ja','en','fr'];
let lang;try{lang=localStorage.getItem(KEY)}catch{}if(!supported.includes(lang)){const browser=(navigator.languages?.[0]||navigator.language||'en').toLowerCase();lang=browser.startsWith('ja')?'ja':browser.startsWith('fr')?'fr':'en'}
const escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const pattern=new RegExp(Object.keys(dictionary).sort((a,b)=>b.length-a.length).map(key=>/[A-Za-z]/.test(key)&&!/[ぁ-龯]/.test(key)?'(?<![A-Za-z])'+escape(key)+'(?![A-Za-z])':escape(key)).join('|'),'g');
const cache=new Map();function t(value){const s=String(value??'');if(lang==='ja')return s;if(cache.has(s))return cache.get(s);let out=dictionary[s]?.[lang];if(out===undefined)out=s.replace(pattern,key=>dictionary[key][lang]??key);if(cache.size>2000)cache.clear();cache.set(s,out);return out}
const originals=new WeakMap(),attrs=new WeakMap();let observer;
function translateNode(node){if(node.nodeType===3){if(node.parentElement?.closest('script,style,select,textarea,[data-no-i18n]'))return;const old=originals.get(node),current=node.nodeValue,source=old&&old.output===current?old.source:current,output=t(source);originals.set(node,{source,output});if(current!==output)node.nodeValue=output;return}if(node.nodeType!==1)return;if(node.matches('script,style,select,textarea,[data-no-i18n]'))return;for(const attr of ['title','aria-label','alt','placeholder'])if(node.hasAttribute(attr)){let saved=attrs.get(node)||{};const current=node.getAttribute(attr),old=saved[attr],source=old&&old.output===current?old.source:current,output=t(source);saved[attr]={source,output};attrs.set(node,saved);if(output!==current)node.setAttribute(attr,output)}for(const child of node.childNodes)translateNode(child)}
const config={childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','alt','placeholder']};function refresh(){observer?.disconnect();translateNode(document.documentElement);document.documentElement.lang=lang;document.documentElement.dataset.language=lang;document.documentElement.style.setProperty('--almost-label',JSON.stringify(t('もうすぐ達成！')));document.documentElement.style.setProperty('--mission-label',JSON.stringify(t('ミッション達成！')));observer?.observe(document.documentElement,config)}
function setLanguage(next){if(!supported.includes(next))return;lang=next;cache.clear();try{localStorage.setItem(KEY,next)}catch{}refresh();document.querySelectorAll('[data-language-select]').forEach(s=>s.value=lang);window.dispatchEvent(new CustomEvent('hamusubi-language',{detail:lang}))}
window.I18n={t,setLanguage,get language(){return lang},refresh,KEY};
// Canvas HUD, speech and exported shelf captions use the same dictionary.
const proto=CanvasRenderingContext2D.prototype,fill=proto.fillText,stroke=proto.strokeText,measure=proto.measureText;
proto.fillText=function(value,x,y,maxWidth){return maxWidth===undefined?fill.call(this,t(value),x,y):fill.call(this,t(value),x,y,maxWidth)};
proto.strokeText=function(value,x,y,maxWidth){return maxWidth===undefined?stroke.call(this,t(value),x,y):stroke.call(this,t(value),x,y,maxWidth)};
proto.measureText=function(value){return measure.call(this,t(value))};
function init(){const control=document.createElement('label');control.id='language-control';control.dataset.noI18n='';control.innerHTML='<span>Language / 言語</span><select data-language-select aria-label="Language / 言語"><option value="ja">日本語</option><option value="en">English</option><option value="fr">Français</option></select>';document.querySelector('#title-screen').append(control);const select=control.querySelector('select');select.value=lang;select.onchange=()=>setLanguage(select.value);const title=document.createElement('span');title.className='localized-logo';title.dataset.noI18n='';title.textContent='Hamusubi';document.querySelector('#title-screen h1').append(title);observer=new MutationObserver(records=>{observer.disconnect();const roots=new Set();for(const r of records){if(r.type==='childList')for(const n of r.addedNodes)roots.add(n);else roots.add(r.target)}for(const n of roots)if(n.isConnected)translateNode(n);observer.observe(document.documentElement,config)});refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
