(()=>{'use strict';
const names=['風そよぐ むすびの丘','おはなの草原','きらきら渓流','風車の高原','夕焼け吊り橋','あじさい雨の森','星降る湖','もみじの谷','雪ふる白い丘','はむすびの里'];
const gifts=['白い小花の飾り','カラフルな花飾り','きらきら小石のオブジェ','小さな風車のおもちゃ','夕焼け色のリボン','あじさいの壁飾り','星のガーランド','もみじの飾り','雪の結晶の飾り','はむすびの記念オブジェ'];
const icons=['✿','❀','◆','✣','🎀','❁','★','🍁','❄','🍙'];
const tips=['10この はむすびを 赤い旗へ とどけよう。','お花の道は、上からも下からも。','おなかが すいたら、おやつで ひとやすみ。','ライバルハムも はむすびが大好き。ふれると ぽよん！','夕焼けの橋を ゆっくり おさんぽ。','雨つぶと あじさいを 楽しもう。','月あかりの下、光る道を たどろう。','もみじの谷を 上へ、下へ。','青い氷は すこし すべるよ。','みんなが待っている はむすびの里へ！'];
// Terrain lives in routes.js; this module owns metadata and durable progress.
const stages=names.map((name,id)=>({id,name,gift:gifts[id],icon:icons[id],tip:tips[id],hunger:true,platforms:[],extras:[],seeds:[],checkpoints:[],rivalPlatforms:[]}));
const KEY='hamusubi.journey.v1';const fresh=()=>({version:3,currentStage:null,lastClearedStage:null,world10Cleared:false,lapStartStage:0,adventureStage:0,keys:0,plays:0,bonusClaims:0,bonusTopScores:[],totalScore:0,homeKeyFound:false,chestTutorial:false,homeKeyRollAt:0,unlocked:1,cleared:Array(10).fill(false),best:Array(10).fill(0),gifts:Array(10).fill(false),ending:false,clearCounts:Array(10).fill(0),topScores:Array.from({length:10},()=>[]),collection:[],favorites:[],care:{hunger:100,lives:3,snacks:3}});
let storageOK=true;
function normalize(raw){const s=fresh();if(!raw||typeof raw!=='object')return s;for(let i=0;i<10;i++){s.cleared[i]=raw.cleared?.[i]===true;s.best[i]=Math.max(0,Math.min(999,Math.floor(Number(raw.best?.[i])||0)));s.gifts[i]=raw.gifts?.[i]===true||s.cleared[i];if(s.cleared[i])s.best[i]=Math.max(10,s.best[i]);}s.unlocked=Math.max(1,Math.min(10,Math.floor(Number(raw.unlocked)||1)));for(let i=0;i<9;i++)if(s.cleared[i])s.unlocked=Math.max(s.unlocked,i+2);s.ending=raw.ending===true;for(let i=0;i<10;i++)s.clearCounts[i]=Math.max(s.cleared[i]?1:0,Math.min(9999,Math.floor(Number(raw.clearCounts?.[i])||0)));for(let i=0;i<10;i++)s.topScores[i]=(Array.isArray(raw.topScores?.[i])?raw.topScores[i]:Array(Math.min(3,s.clearCounts[i])).fill(1000)).filter(n=>Number.isFinite(n)&&n>=0).map(Math.floor).sort((a,b)=>b-a).slice(0,3);for(const k of ['keys','plays','bonusClaims','totalScore','homeKeyRollAt'])s[k]=Math.max(0,Math.min(Number.MAX_SAFE_INTEGER,Math.floor(Number(raw[k])||0)));if(raw.plays===undefined)s.plays=s.clearCounts.reduce((a,b)=>a+b,0);s.bonusClaims=Math.min(s.bonusClaims,Math.floor(s.plays/50));s.homeKeyFound=raw.homeKeyFound===true;s.chestTutorial=raw.chestTutorial===true;s.bonusTopScores=(Array.isArray(raw.bonusTopScores)?raw.bonusTopScores:[]).filter(n=>Number.isFinite(n)&&n>=0).map(Math.floor).sort((a,b)=>b-a).slice(0,3);s.collection=HAMUKETSU.filter(c=>s.clearCounts[Number(c.stage.split('-')[1])-1]>=Number(c.clear_count)).map(c=>c.collection_id);s.favorites=[...new Set(Array.isArray(raw.favorites)?raw.favorites:s.collection.slice(0,10))].filter(id=>s.collection.includes(id)).slice(0,10);s.care={hunger:Math.max(0,Math.min(100,Number(raw.care?.hunger)??100)),lives:Math.max(0,Math.min(3,Math.floor(Number(raw.care?.lives)??3)))};if(!Number.isFinite(s.care.hunger))s.care.hunger=100;if(!Number.isFinite(s.care.lives))s.care.lives=3;s.care.snacks=Number.isFinite(raw.care?.snacks)?Math.max(0,Math.min(3,Math.floor(raw.care.snacks))):3;
const valid=id=>Number.isInteger(id)&&id>=0&&id<s.unlocked;
s.world10Cleared=raw.world10Cleared===true||s.cleared[9]||s.ending;s.lapStartStage=0;
s.lastClearedStage=valid(raw.lastClearedStage)?raw.lastClearedStage:s.cleared.lastIndexOf(true)>=0?s.cleared.lastIndexOf(true):null;
s.currentStage=valid(raw.currentStage)?raw.currentStage:null;
s.adventureStage=s.currentStage??(valid(raw.adventureStage)?raw.adventureStage:s.world10Cleared?0:s.unlocked-1);
return s}
let progress;try{progress=normalize(JSON.parse(localStorage.getItem(KEY)||'null'))}catch{progress=fresh();storageOK=false}
function save(){try{if(!localStorage.getItem(KEY+'.before-missions')){const old=localStorage.getItem(KEY);if(old)localStorage.setItem(KEY+'.before-missions',old)}localStorage.setItem(KEY,JSON.stringify(progress));storageOK=true}catch{storageOK=false}return storageOK}
function record(id,count){if(count>progress.best[id]){progress.best[id]=count;save()}}
function clear(id,score=1000,collected=10){progress.lastClearedStage=id;progress.currentStage=null;progress.adventureStage=(id+1)%10;if(id===9){progress.world10Cleared=true;progress.lapStartStage=0;}progress.totalScore+=Math.max(0,Math.floor(Number(score)||0));progress.topScores[id].push(Math.max(0,Math.floor(Number(score)||0)));progress.topScores[id].sort((a,b)=>b-a);progress.topScores[id]=progress.topScores[id].slice(0,3);const first=!progress.gifts[id];progress.clearCounts[id]++;const reward=HAMUKETSU.find(c=>c.stage==='1-'+(id+1)&&Number(c.clear_count)===progress.clearCounts[id]);if(reward&&!progress.collection.includes(reward.collection_id))progress.collection.push(reward.collection_id);progress.cleared[id]=true;progress.best[id]=Math.max(progress.best[id],collected);progress.gifts[id]=true;progress.unlocked=Math.max(progress.unlocked,Math.min(10,id+2));save();return first}
window.Journey={stages,get progress(){return progress},get storageOK(){return storageOK},save,record,clear,addKey(){progress.keys++;save()},takeKey(){if(progress.keys<1)return false;progress.keys--;save();return true},startAdventure(id=progress.adventureStage){progress.currentStage=id;progress.adventureStage=id;progress.plays++;save()},get bonusAvailable(){return Math.floor(progress.plays/50)>progress.bonusClaims},claimBonus(){if(!this.bonusAvailable)return false;progress.bonusClaims++;save();return true},clearBonus(score){progress.bonusTopScores.push(score);progress.bonusTopScores.sort((a,b)=>b-a);progress.bonusTopScores=progress.bonusTopScores.slice(0,3);progress.totalScore+=score;save()},toggleFavorite(id){if(!progress.collection.includes(id))return false;const index=progress.favorites.indexOf(id);if(index>=0)progress.favorites.splice(index,1);else if(progress.favorites.length<10)progress.favorites.push(id);else return false;save();return true},replaceFavorite(oldId,newId){const i=progress.favorites.indexOf(oldId);if(i<0||!progress.collection.includes(newId)||progress.favorites.includes(newId))return false;progress.favorites.splice(i,1,newId);save();return true},completeEnding(){progress.ending=true;save()},erase(){progress=fresh();save()},normalize,KEY};
})();

