(()=>{'use strict';const E=EventSystem,$=s=>document.querySelector(s),campaigns=window.HAMUSUBI_CAMPAIGNS||[];
const t=s=>window.I18n?I18n.t(s):s;
const titles=[
{id:'album30',name:'はむケツマイスター',condition:'ハムケツを30個獲得',test:()=>Journey.progress.collection.length>=30},
{id:'world10',name:'おでかけマスター',condition:'通常ステージをすべてクリア',test:()=>Journey.progress.cleared.slice(0,10).every(Boolean)},
{id:'fur5',name:'おしゃれフリーク',condition:'毛色を5回変更',test:()=>E.data.changes.fur>=5},
{id:'furniture5',name:'ハウジングラバー',condition:'家具を5回入れ替える',test:()=>E.data.changes.furniture>=5},
...campaigns.flatMap(c=>(c.titles||[]).map(a=>({...a,test:()=>a.stages.every(id=>E.record(id).clears>0)})))];
function titleNews(){const plate=$('#equipped-title');if(plate){const label='🏅 '+t(titleName());if(plate.textContent!==label)plate.textContent=label;}const unread=titles.some(a=>E.data.titles[a.id]&&!E.data.titles[a.id].seenAt);for(const selector of ['#records','#equipped-title']){const node=$(selector);if(node){node.classList.toggle('has-title-news',unread);node.setAttribute('aria-description',unread?'新しい称号があります':'')}}return unread}
function checkTitles(){let changed=false;for(const a of titles)if(!E.data.titles[a.id]&&a.test()){E.data.titles[a.id]={acquiredAt:new Date().toISOString()};Missions.queue.push('🏅 '+a.name+'を手に入れた！');changed=true}if(changed)E.save();titleNews()}
function changed(kind){const key=kind==='fur'?'fur':'furniture';E.data.changes[key]++;checkTitles();E.save()}
function rainbow(eventId){const e=E.current;if(!eventId||!e||e.eventId!==eventId||!E.active(e))return;const r=E.data.campaignStats[e.campaignId]||={rainbow:0};r.rainbow++;E.save()}
function button(parent,label,fn,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=fn;parent.append(b);return b}
function panel(title,page){HomeGame.release();const p=$('#upgrade-panel');p.classList.remove('compact-share');p.dataset.page=page;p.hidden=false;p.scrollTop=0;$('#upgrade-title').textContent=title;const b=$('#upgrade-body');b.replaceChildren();return b}
function showCampaign(id){
 const c=campaigns.find(c=>c.eventId===id);if(!E.active(c)){HomeGame.notice('このイベントは終了しました。');return}
 E.award(E.definitions.find(e=>e.campaignId===id));const body=panel(c.name,'campaign');body.dataset.campaign=id;
 const el=(tag,cls,text,parent)=>{const n=document.createElement(tag);n.className=cls;if(text)n.textContent=text;if(parent)parent.append(n);return n};
 const header=el('header','moon-header','',body);button(header,'‹ もどる',()=>HomeUpgrade.close());
 const heading=el('div','moon-heading','',header);el('h2','',c.name,heading);el('p','','～ お月さままで、おでかけ。～',heading);
 const date=el('div','moon-date','',header);el('b','','開催期間',date);el('span','',c.period,date);
 const greeting=el('div','moon-greeting','',header);el('p','','お月さまと一緒に\n特別な秋の冒険へ！',greeting);const hamster=el('img','moon-hamster','',greeting);hamster.src='assets/events/moon2026/header-hamster.png';hamster.alt='月と雲に乗ったはむすび';
 const content=el('div','moon-content','',body);
 for(const mode of ['normal','hard']){const section=el('section','season-section '+mode,'',content);const heading=el('div','moon-section-heading','',section);el('h3','',mode==='normal'?'🌸 NORMAL':'✿ HARD',heading);el('p','',mode==='normal'?'ストーリーを進めながらお月さまへの道を楽しもう！':'各ステージのNORMALをクリアすると、対応するHARDに挑戦できるよ！',heading);const row=el('div','season-routes','',section);
 for(const e of E.definitions.filter(e=>e.campaignId===id&&e.mode===mode)){const r=E.record(e.eventId),locked=!E.unlocked(e),card=button(row,'',()=>{HomeUpgrade.close();HomeGame.beginEvent(e.eventId)},!E.eligible(e));card.className='season-stage'+(locked?' locked':'');card.setAttribute('aria-label',e.name+(locked?' '+E.unlockCondition(e):''));const art=el('div','moon-stage-art','',card);const img=el('img','','',art);img.src=e.background;img.alt='';el('strong','moon-stage-name',e.number+'　'+e.name.split(' · ')[0],art);if(locked){const lock=el('div','moon-lock','',art);el('b','','🔒',lock);el('span','',E.unlockCondition(e),lock)}if(r.clears)el('span','moon-clear','CLEAR!',art);const stats=el('div','moon-stage-stats','',card);const count=el('span','moon-rice-count','',stats),icon=el('canvas','moon-rice-icon','',count);icon.width=40;icon.height=40;icon.setAttribute('role','img');icon.setAttribute('aria-label','はむすび');const ctx=icon.getContext('2d');ctx.translate(20,23);for(const [points,color] of [[[[-15,12],[-17,4],[-12,-7],[-5,-18],[3,-20],[10,-12],[18,5],[16,12]],'#67492e'],[[[-12,9],[-13,2],[-8,-8],[-2,-16],[3,-16],[12,0],[14,9]],'#fff9df']]){ctx.fillStyle=color;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}ctx.fillStyle='#263b32';ctx.fillRect(-5,0,11,12);ctx.fillStyle='#486044';ctx.fillRect(-3,2,3,8);ctx.fillStyle='#fff';ctx.fillRect(-7,-7,3,3);count.append(document.createTextNode(r.bestRice+' 個'));el('span','','ベストスコア　'+(r.bestScore||'—'),stats);if(r.clears)el('small','moon-clear-count',r.clears+'回クリア',stats)} }
 const awards=el('section','moon-awards','',content),rewards=el('div','moon-reward-area','',awards);el('h3','','🎁 イベント報酬',rewards);const grid=el('div','moon-reward-grid','',rewards);
 const labels={normalAll:'NORMALの全3ステージをクリア',campaignScore:'イベントでベストスコア9,000点以上',any:'イベントステージで虹のはむすびを1個獲得、またはイベントステージを累計50回クリア（NORMAL・HARD共通）',complete:'3つのイベントミッションを達成'};
 for(const r of E.rewards.filter(r=>r.eventId===id)){const owned=!!E.data.owned[r.rewardId],card=el('article','moon-reward'+(owned?' owned':''),'',grid),visual=el('div',owned?'moon-reward-visual':'moon-reward-visual reward-mystery','',card);visual.append(E.preview(r));visual.dataset.category=r.category;if(!owned){el('b','','?',visual);visual.setAttribute('aria-label','未取得報酬')}el('strong','',r.name,card);el('p','',labels[r.condition.type],card);el('small','',owned?'✓ 取得済み':r.condition.type==='any'?'虹 '+Math.min(E.campaignValue('periodRainbow',id),1)+' / 1　または　クリア '+Math.min(E.campaignValue('campaignClears',id),50)+' / 50':Math.min(E.campaignValue(r.condition.type,id),r.condition.target)+' / '+r.condition.target,card);}
 const titleArea=el('aside','moon-title-area','',awards);el('h3','','♕ 限定称号',titleArea);el('p','','HARDクリア報酬',titleArea);for(const a of c.titles||[]){const owned=!!E.data.titles[a.id],item=el('div','moon-title-reward'+(owned?' owned':''),'',titleArea);el('strong','',(owned?'🏅 ':'？ ')+a.name,item);el('small','',a.condition,item)}
}

E.decorate=()=>{const b=$('#upgrade-body');for(const c of campaigns.filter(c=>E.active(c))){const card=button(b,'',()=>showCampaign(c.eventId));card.className='event-entry';const img=document.createElement('img');img.src='assets/events/moon2026/meadow.png';img.alt='';const copy=document.createElement('span'),title=document.createElement('strong'),date=document.createElement('small'),sub=document.createElement('span');title.textContent=c.name;date.textContent=c.period;sub.textContent='お月さままで、おでかけ。';copy.append(title,sub,date);const arrow=document.createElement('b');arrow.textContent='›';card.append(img,copy,arrow)}};
E.show=id=>showCampaign(E.definitions.find(e=>e.eventId===id)?.campaignId||id);
function bowls(){const b=panel('ごはん皿','bowl');button(b,'‹ カスタムにもどる',()=>HomeUpgrade.housing());const defaults=document.createElement('div');defaults.className='upgrade-grid design-grid';b.append(defaults);const defaultCard=button(defaults,'',()=>{if(E.selected('bowl'))changed('bowl');E.clearSelection('bowl');E.paintSelection('bowl',b)});defaultCard.dataset.customId='wood';defaultCard.append(Customize.preview('bowl','wood'));const label=document.createElement('strong');label.textContent='いつものごはん皿';defaultCard.append(label);E.customCards('bowl',b)}
function titleName(){return titles.find(a=>a.id===E.data.equippedTitle)?.name||'称号　－－'}
function updateTitleSelection(){for(const row of document.querySelectorAll('#upgrade-body .title-item[data-title-id]')){const id=row.dataset.titleId,owned=!!E.data.titles[id],equipped=E.data.equippedTitle===id;row.classList.toggle('equipped',equipped);row.classList.toggle('owned',owned&&!equipped);const control=row.querySelector('button');control.textContent=equipped?'✓ 使用中':owned?'装備する':'🔒 未取得';control.setAttribute('aria-pressed',String(equipped));}titleNews()}
function showTitles(){checkTitles();const newly=new Set(titles.filter(a=>E.data.titles[a.id]&&!E.data.titles[a.id].seenAt).map(a=>a.id));const b=panel('称号一覧','titles');button(b,'称号をつけない',()=>{E.data.equippedTitle=null;E.save();updateTitleSelection()});for(const a of titles){const owned=E.data.titles[a.id],p=document.createElement('article');p.dataset.titleId=a.id;p.className='title-item '+(E.data.equippedTitle===a.id?'equipped':owned?'owned':'locked');const info=document.createElement('p');info.textContent=(owned?'取得済み · '+a.name:'🔒 未取得')+' · '+a.condition+(owned?' · '+new Date(owned.acquiredAt).toLocaleDateString():'');if(newly.has(a.id)){p.classList.add('title-new');const badge=document.createElement('b');badge.className='title-new-label';badge.textContent='NEW!';p.append(badge)}p.append(info);button(p,E.data.equippedTitle===a.id?'✓ 使用中':owned?'装備する':'🔒 未取得',()=>{E.data.equippedTitle=a.id;E.save();updateTitleSelection()},!owned);b.append(p)}for(const id of newly)E.data.titles[id].seenAt=new Date().toISOString();if(newly.size)E.save();updateTitleSelection();button(b,'たびのきろくにもどる',()=>{HomeUpgrade.close();$('#records').click()});button(b,'閉じる',()=>HomeUpgrade.close())}
$('#records').addEventListener('click',()=>{checkTitles();$('#equipped-title')?.remove();const b=button($('#list-title').parentElement,'🏅 '+titleName(),showTitles);b.id='equipped-title';titleNews();$('#list-title').insertAdjacentElement('afterend',b);const host=$('#stage-list');const heading=document.createElement('h3');heading.textContent='イベントのきろく';host.append(heading);for(const c of campaigns){const details=document.createElement('details');details.className='event-records';details.open=true;const summary=document.createElement('summary');summary.textContent=(c.decoration||'🌙')+' '+c.name;details.append(summary);const date=document.createElement('p');date.textContent=c.period;details.append(date);for(const mode of ['normal','hard']){const h=document.createElement('h4');h.textContent=mode.toUpperCase();details.append(h);const table=document.createElement('table');table.className='record-table event-record-table';const head=table.createTHead().insertRow();for(const label of ['ステージ','クリア回数','最高はむすび','ベストスコア','SCORE TOP 3']){const th=document.createElement('th');th.textContent=label;head.append(th)}const tbody=table.createTBody();for(const e of E.definitions.filter(e=>e.campaignId===c.eventId&&e.mode===mode)){const r=E.record(e.eventId),tr=tbody.insertRow();for(const text of [e.number+'. '+e.name.split(' · ')[0],r.clears+'回',r.bestRice+'個',r.bestScore||'—',r.top.length?r.top.join(' / '):'— / — / —'])tr.insertCell().textContent=text}details.append(table)}host.append(details)}const share=button(host,'たびのきろくをシェア',()=>{HomeUpgrade.close();$('#share-open').click();const text=t('はむすび')+(E.data.equippedTitle?' · 🏅 '+t(titleName()):'')+' · SCORE '+Journey.progress.totalScore;$('#share-x').href='https://twitter.com/intent/tweet?text='+encodeURIComponent(text)+'&url='+encodeURIComponent(location.href.split('?')[0]);$('#share-line').href='https://line.me/R/msg/text/?'+encodeURIComponent(text+'\n'+location.href.split('?')[0]);$('#share-status').textContent=text});share.className='record-share'});

$('#select').addEventListener('click',()=>$('#equipped-title')?.remove());
const eventNav=document.createElement('button');eventNav.id='event-nav';eventNav.innerHTML='<span>🌙</span>イベント';$('.home-menu').append(eventNav);eventNav.onclick=()=>{const active=campaigns.filter(c=>E.active(c));HomeGame.release();if(active.length===1)showCampaign(active[0].eventId);else{const b=panel('開催中のイベント','events');for(const c of active)button(b,c.name,()=>showCampaign(c.eventId))}};
const badge=document.createElement('button');badge.id='season-title';$('#title-screen').append(badge);const deco=document.createElement('img');deco.id='season-decoration';deco.alt='';deco.src='assets/events/moon2026/title-decoration.png';$('#title-screen').append(deco);const period=document.createElement('span');period.id='season-playing-period';$('#stage').append(period);
function refresh(){const c=campaigns.find(c=>E.active(c));badge.hidden=!c;deco.hidden=!c;eventNav.hidden=!c;$('.home-menu').classList.toggle('with-event',!!c);if(c){badge.textContent=(c.decoration||'★')+' '+c.name+' 開催中！\n'+c.period;badge.onclick=()=>{HomeGame.goHome();showCampaign(c.eventId)}}const running=E.current;if(running&&!E.active(running)){HomeGame.goHome();HomeGame.notice('このイベントは終了しました。')}period.hidden=!running||!['play','pause','win','hungry','feeding'].includes(HomeGame.mode());if(running)period.textContent=running.period;if($('#upgrade-panel').dataset.page==='campaign'&&!$('#upgrade-panel').hidden&&!E.active(campaigns.find(c=>c.eventId===$('#upgrade-body').dataset.campaign)))HomeUpgrade.close();checkTitles()}
function ground(g,p,camera,stage,H,offset){const x=p.x-camera;if(stage.theme==='moon-meadow')return false;g.save();if(stage.theme==='moon-sky'){g.fillStyle='#9f9ccf';g.beginPath();g.roundRect(x,p.y,p.w,28,14);g.fill();g.fillStyle='#e8e6ff';g.beginPath();g.roundRect(x,p.y,p.w,17,8);g.fill();for(let i=14;i<p.w;i+=28){g.fillStyle='#f8f5ff';g.beginPath();g.ellipse(x+i,p.y+7,17,8,0,0,7);g.fill()}}else{const depth=p.oneWay?28:Math.max(30,H-offset-p.y+4);g.fillStyle='#77758e';g.fillRect(x,p.y,p.w,depth);g.fillStyle='#cbc9de';g.fillRect(x,p.y,p.w,9);g.fillStyle='#9491ae';for(let y=22;y<depth;y+=30)for(let a=18;a<p.w-12;a+=48){g.beginPath();g.ellipse(x+a,p.y+y,12,5,0,0,7);g.fill()}}g.restore();return true}

window.Seasonal={checkTitles,changed,rainbow,bowls,showCampaign,titles,ground};checkTitles();refresh();setInterval(refresh,1000);document.addEventListener('visibilitychange',refresh);
})();
