// Optional discoveries. Stage rules and original presentation stay in game.js.
(()=>{'use strict';
const values={normal:100,sparkle:300,gold:500,rainbow:1000};
function shuffle(xs,rng=Math.random){const a=[...xs];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function loot(rng=Math.random,eventHard=false){const n=rng();return n<.2?[]:n<(eventHard?.82:.85)?['normal','normal','normal']:n<(eventHard?.97:.98)?['gold']:['rainbow']}
function rice(x,y,kind='normal'){return {x,y,homeX:x,homeY:y,kind,taken:false,held:false,cool:0}}
// Roll outing keys per run on stationary, reachable route surfaces, away from chests.
function outingKeys(stage,rng){const range=stage.keyCountRange,target=range?range[0]+Math.floor(rng()*(range[1]-range[0]+1)):stage.keys.length;const pool=[...stage.platforms,...stage.extras].filter(p=>!p.moving&&p.w>=100).flatMap(p=>{const out=[];for(let x=Math.max(240,p.x+45);x<=Math.min(stage.end-200,p.x+p.w-45);x+=40){const y=p.y-30;if(stage.chests.some(([cx,cy])=>Math.abs(cx-x)<85&&Math.abs(cy-y)<85))continue;if([...stage.platforms,...stage.extras].some(q=>q!==p&&!q.oneWay&&q.x<x+20&&q.x+q.w>x-20&&q.y<p.y&&q.y>y-40))continue;out.push({x,y,taken:false})}return out});const selected=[];for(const k of shuffle(pool,rng)){if(selected.length>=target)break;if(selected.every(q=>Math.abs(q.x-k.x)>120))selected.push(k)}return selected;}
function candidates(stage){return [...stage.platforms,...stage.extras].filter(p=>!p.moving&&p.w>=150).flatMap(p=>{const out=[];for(let x=p.x+50;x<=p.x+p.w-50;x+=30){if(x<240||x>stage.end-250)continue;if(stage.seeds.some(([rx,ry])=>Math.abs(rx-x)<82&&Math.abs(ry-(p.y-24))<65))continue;if([...stage.platforms,...stage.extras].some(q=>q!==p&&!q.moving&&!q.oneWay&&q.x<x+45&&q.x+q.w>x-45&&q.y<p.y&&q.y>p.y-110))continue;out.push({x,y:p.y})}return out})}
function start(stage,bonus=false,rng=Math.random){if(stage.outing!==undefined||stage.eventRoute)return {keys:outingKeys(stage,rng),chests:stage.chests.map(([x,y],id)=>({x,y,id,open:false,age:0,rewards:[]})),bonusKeys:0,eventHard:stage.eventRoute===true&&stage.eventDifficulty==='hard'};const pool=shuffle(candidates(stage),rng);const keyN=bonus?4:stage.id<3?1:stage.id<7?2:3,chestN=bonus?12:stage.id<3?2:stage.id<7?4:6;const selected=[];if(stage.id===0&&!Journey.progress.chestTutorial){const first=candidates(stage).filter(p=>p.y===stage.platforms[0].y&&p.x<stage.platforms[0].x+stage.platforms[0].w).sort((a,b)=>a.x-b.x)[0];if(first)selected.push(first)}for(const p of pool){if(selected.length>=chestN)break;if(selected.every(q=>Math.abs(p.x-q.x)>(bonus?95:140)||Math.abs(p.y-q.y)>110))selected.push(p)}const keyPool=shuffle([...stage.platforms,...stage.extras].filter(p=>!p.moving&&p.w>=100&&p.x>200&&p.x+p.w<stage.end-200).map(p=>({x:p.x+p.w*.5,y:p.y-30})),rng);const keys=[];for(const k of keyPool){if(keys.length>=keyN)break;const p=[k,{...k,x:k.x-55},{...k,x:k.x+55}].find(k=>selected.every(c=>Math.abs(c.x-k.x)>70||Math.abs(c.y-24-k.y)>65));if(p)keys.push({...p,taken:false})}
if(bonus){keys.length=0;const spots=[{p:stage.platforms[1],lift:30},{p:stage.platforms[5],lift:30},{p:stage.extras[1],lift:45},{p:stage.extras[4],lift:65}];if(rng()<.5)spots.push({p:stage.extras[2],lift:50});for(const {p,lift} of spots){const options=shuffle([.2,.4,.6,.8],rng).map(f=>({x:p.x+p.w*f,y:p.y-lift,taken:false}));keys.push(options.find(k=>selected.every(c=>Math.abs(c.x-k.x)>65||Math.abs(c.y-24-k.y)>60))||options[0]);}}
return {keys,chests:selected.map((p,id)=>({...p,id,open:false,age:0,rewards:[]})),bonusKeys:bonus?3:0}}
function open(run,chest,rng=Math.random){if(!chest||chest.open)return null;if(run.bonusKeys>0)run.bonusKeys--;else if(!Journey.takeKey())return null;chest.open=true;chest.age=0;chest.rewards=loot(rng,run.eventHard===true);window.Missions?.add('chests');const first=!Journey.progress.chestTutorial;Journey.progress.chestTutorial=true;Journey.save();return {kinds:chest.rewards,first}}
function homeKey(rng=Math.random,now=Date.now()){const p=Journey.progress;if(!p.homeKeyFound)return {x:600,y:365,taken:false,first:true};if(now-p.homeKeyRollAt<60000)return null;p.homeKeyRollAt=now;Journey.save();return rng()<.14?{x:[150,300,630,815][Math.floor(rng()*4)],y:365,taken:false,first:false}:null}
window.Treasure={values,rice,start,open,homeKey,loot,shuffle};
})();
